version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/development
      dockerfile: nginx.docker
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/development
      dockerfile: php-fpm.docker
    volumes:
      - .:/app
  php-cli:
    container_name: php-cli
    build:
      context: ./docker/development
      dockerfile: php-cli.docker
    volumes:
      - .:/app
      - composer:/root/.composer/cache

volumes:
  composer: